language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: a8UVtPjIHCf2US4w88URZv+LFK52AhX77Hyz7XMPibnb83fK1zFEL+Jj5SHwGziiBs/FCFv5EFJ+K/4zHtbGyGWRcsZgnCi6Z0+mUwAQTwWWCsrbCbjhUM+tM5Jou1tw5+1FJ3xPiCFcufdAQzOjDUazOlwTiiSTUmZkwBzPuoeG+3F9cX3Occ42JJOH5LGHmhw+bITn2qM1gAgIG0IG4S5ImRaMGHTBcRNazmL1gvjmwB7nJLuimQ+cTH2QKnn3RjDK0Z/wDk9Hv61lEfkSPQfrRzuFFbRgstTWJP06mmYAuwCXoqxh3kEZDAlng0jYpBfGoVBI7HIk/OxW9AyHKnqf9oatevIpNUFtuNKsHa9BgyNBJJMdcw4vBn2t+WY7iZ/t+PS8TdPseqDszApyynZ+tkGOtYcNv16/dBR8Gp6J845wGqbi2e3qFFX//2gcutf/CZiz/02pxCRPHYRAfcmPKMb8M2h3VZax0Ib6yFfj5jzBowU9jOF/yJp1WEXjpec1EFK4UDS/lCel/2oWLf9obREJfE4+ip+rfRrXpWbEMMhg3su5X0pZ4HL2Xd5vSA1GsH6g6I8xX8B0/+TWZMArOI6fkM1ju+fxuHP0lN8OQTw6ntWxJ6uJuywo4vOdUm0LginMOCHIIzGjW0yCiVGTmcEwUa2iMC34SrV3QMs=
  - secure: KlO3MXyvSvAVv/ZsXYoeBHu3CbFPdDjAEpsmpYLX7uPer9tNyj23Tm5SMUHOI6jrxkkKRgLzwoMvKNM+6iJz+o5rdJUI7YZg+0FVTfmJ6wVsTh9fwPX3Ecrk4N43G13SIOwcHZB19IE6/+Q2nKzTUqO0NvjAX2+kVUj3yphFKRJgi4WafIuUNouiY8sVkrHfgI7JgII7CdpFF4BM525KJwLWOz0GGlcsX018ZDgUyHglz5Hzpaj1ianOxQKDMlWxW0re9RB9UWK7I+wDu7WW46SVUpl/jO8dI68v4lEt47VeAml3CGsuEAclNqLHjjR7hcEJMc0Q8c/5Qf1aiBUBo8QAENeMXSx4/dvEROe1d0nNlzsPWDDfJsTgCDkc8mT6gYx+9WSDFL+P1UQJczwHz0n2gqM9edvCcIabiCjGMGDpgZyJGnVvTSONI1dQ8Ay165Cs7PpPx3k4t47o2nweUywvI3lB1F56H/vjwt0wiRV5GE0HAo87GXRijrjJgJybH2nfNWEM/hUiL7yvwqT41rN7vgKJV0QxgEUN29LCa4rGhsIMKpy91lNcSzbCHr22P/UcXfpyrp0m0Gda65mGPUCIJH6q+CgS+DFrAbo0ai789fNUd/qffxVWyqCxP+UjGh7UFkJQZGQ0GY7O691ltbZcH2HldyUTIZkIkXUpMv4=
  - secure: TGbdAeLHWP9LKBVWPtY0lZle4OROAXtSbKHkwJFpvtiPYE85qqNsLpoZSt0j7Qs98j5dXClY5obSKj5UCNazDC23Lhj1fble8vscxiOiizfJtyKzd1GmT73Z4yVC0POcADC3dwqfO8nSZdZ6cdSPFuDWtvExUQclYzVut19paSIn9Yq7Vx4vVTMFPqId6JcPY/OQfy8HPKChzwnfXOB+HjGTVy4oEMr733Z3C2/Qy7VRwgSbIKXxMrq5OBilX8iJRkjIdTjUTS0Urw0qpNaI5LKzqRYelkiym2jN8BHKqdhY4ZSktZpTqxTzmXi7ezV2OwgAucO3fDP8F1upb8fTyTneoiq9L9g+P6xNblbbJXFndBvgQx2jdZ9YM7d5LOGwgwtH6A1Sy4a6p3+xa3WjnTC1LSW59YWh1DTHaZpH+FsqTzTYJm5K+FhIXnFo1KPaAJindrUahaBxP7un5yLV1z2LR+Y0Nengwt2Jr/nlUq0EDmdGmwHY+JVMTcpbamlgj2vScH8ehdHwOyNxxgeO64nkfvRoQ0DZo36+HpgHYx289SoeftLwctmPljk0nCbCRQWbxtUeZ8AJLmpavMsudUJj3kHn8ypxPYrcumznwAcGytXzQkSCsYBOJdD0JkeYEADl+D0QsAHN2K2KYLtnhHxmM+By3xjeJERJxdz5r3c=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: YU0rUfX3QzCPPBmaEuYpb6HLjj5hErbLNW0zb5SeOHZLrGFRzuuADS3XULe1QvNtpiqE4kWu5II3XzxBs4Or/5p3OvrnaRa3pN7yjho4YOpEFF/7fLGt6SkZadwRq8b+BfM1/LoqgHumVWFDx+DHe0urUboz0SRrMMAtoFJpC4YV+kD08S2+67Xz3erekC1IEGaSNot99/xIAoePBeiaqAcuUuXcVjnnDhF8380saxMimuobMbBhkhVh8jn+EwkVMKvxpuzY0xH/uOYhA1g0BUMDXZI5an5AkoLnQwbc4ZWhDjlZnvIjK++4agU3ebPLOB8wff5HIFtY52QUjwuRJNK+JHAp5mso7Nl0pGnOm0zuEEd2ZiFa3nCtLEF27A4tN5si46/tsozR+IsFI5dBUMCLCvYj4TZpjgAcpnH/GySZarm1W8CiSQZYcPchUUggwHuEdXgydE5VXMWeF6G0QQyIX/dfvZGFGAcIw1qHAQLMUz+pgnCBCGbjxb3zS83HUBOb4T1PjGQrOl0zgAQJNt9LvaaWNI5HLqRvhFprnnjr+rRihY2Y0WyJjWtt7lUmB7LaRukpFkYNsh5oHrq0QwxvX85YXlMeX6FMfSLTqBawg4hWYb3/fzdTzumApAtEiR+yq53hsoQWVr2GtdPBuUxUv4enkB/bS+XmkiyAy/s=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
