language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - ATOMIST_REPO_USER=travis-mvn-deploy
  - secure: FA/4Rx1OZ3SSdi8iB1oNTP6uqhEQZ6qv26tb+k+OduKR7Mxq9WFNyvw0PtlFl/vEnwbgf3HuaJw3GFbi90k6pPkWo2GpqyG3z+3h7pkqaE7aTvbBIvAGBntTHr2YpzrWaYOVXMMG2jmNN1ten2S1Yim8vbEZcGoDI3uzduRp+mIC9cbbiOlEo/o91+Uu7s+/dhK4rzgZT+pDMbbkBKooTzgmsDQWaK3O7vbm+rHhPhDol3dqe7eRjjEYY0H6Ys4iGD9f7/OLdSwVwu/ozwjmjVfx/sT9eJt0NSSkyf1jDl1/J6pge2hP50Q0XiNnJY5uUKFVupcF1xMBs5ZbL2KHR1DEJUfVWHKbYxUcVe4K6AfqnhVnOmVz7iO3iGRcs9r/AK7nHCqqytMTdN4PuyN6O2imwMaUcjf9f45oeY/RUWxVyUEdm243d+hoZ0xMUdex+g+m0epgufAf6REFNZ75RPgwfXdZaHzG/H2g7XU9vpI3LfZD6pCUZgxhxw9xUmYg+7osIgpbWlBr3W6mAAH247qjrMxDJx6Q6w+YlBZUA30pQhkZ29/VM/oe7/cFDfZEUwu+k3TeyWhrny4ELCJvuyZRlnXcSAjZfoeHR+gwxX2MNQRNyVu/at0gq4pA2CvkRUCjb6Kh0qd2PRd+rWNIdPlL/2PC1uKjvlV45uscVBQ=
  - secure: hckrnTkWcn+rI+5seB7Wd8JlbO6VAUdEHwnlSJwDRNiiTZpklvMthgwA0YqifMVlZIMowRoTZc9X99alc632qp3omK5was0wiB9x1xCxOyXnJgumyLxww3fGN9+Bd9K9vPm97/wp/oT4epxMNQ6ymEFSHK6sIgRNFgZE3Bts42EOhLcenTCuSKW/Y68vg02sTkrTI8qIjCBNFOdvZg77hkf2hYwRfnc/Mnrb9TMMFuGOve/DLwfYKLTczkuJo/nimOuTGHFJrVPqIt3WiHhe3uT+GQUH+DlYgi1Fhv7EOkvx1CrLHBYY0FvpP9ky/Wh0aud35AwtzNsjlEsSSvIl2W4gsW6+17uhhq2ibgz2LBF7Nv5oHDfyEg7/E+WjQgyaVHFQYsG+KfaJbzQnDpZRTX87rIrhAuTBVAEL99XnuZBQM8b+RVtNfWcQe2L9cy643xNe4YDxJlHvmf+Ys69Y9LfEP1Az2eK53WUNS2evwcVIYvUtmVQiuj+DRisaLa6x6k09HbinI9eoMcx9sYhS/Y8rIqhnJGQKutHw44TUuEqVadvcZJyFvEi28oj/kA24eIOiljqcFHoM3mAhfPl2DXVHm3k6TixIuCYkbaSCwd502Q7WkwaDLBg4TI6j/qku61m/YjCNpPvOiQJWBmFjTL9Xd5GGxrSC7+WG6teudNk=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: YU0rUfX3QzCPPBmaEuYpb6HLjj5hErbLNW0zb5SeOHZLrGFRzuuADS3XULe1QvNtpiqE4kWu5II3XzxBs4Or/5p3OvrnaRa3pN7yjho4YOpEFF/7fLGt6SkZadwRq8b+BfM1/LoqgHumVWFDx+DHe0urUboz0SRrMMAtoFJpC4YV+kD08S2+67Xz3erekC1IEGaSNot99/xIAoePBeiaqAcuUuXcVjnnDhF8380saxMimuobMbBhkhVh8jn+EwkVMKvxpuzY0xH/uOYhA1g0BUMDXZI5an5AkoLnQwbc4ZWhDjlZnvIjK++4agU3ebPLOB8wff5HIFtY52QUjwuRJNK+JHAp5mso7Nl0pGnOm0zuEEd2ZiFa3nCtLEF27A4tN5si46/tsozR+IsFI5dBUMCLCvYj4TZpjgAcpnH/GySZarm1W8CiSQZYcPchUUggwHuEdXgydE5VXMWeF6G0QQyIX/dfvZGFGAcIw1qHAQLMUz+pgnCBCGbjxb3zS83HUBOb4T1PjGQrOl0zgAQJNt9LvaaWNI5HLqRvhFprnnjr+rRihY2Y0WyJjWtt7lUmB7LaRukpFkYNsh5oHrq0QwxvX85YXlMeX6FMfSLTqBawg4hWYb3/fzdTzumApAtEiR+yq53hsoQWVr2GtdPBuUxUv4enkB/bS+XmkiyAy/s=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
